name: Reviewdog Golangci-lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.go"

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: goimports
        run: |
          go install github.com/momotaro98/strictgoimports/cmd/strictgoimports@latest
          strictgoimports -w .
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply Code formatter changes"
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          golangci_lint_version: v1.56.2
          golangci_lint_flags: "--config=.golangci.yml"
          filter_mode: nofilter
          reporter: github-pr-review
          workdir: .
